filetype plugin indent on

set nomodeline
set nocompatible              " required
filetype off                  " required
" Plug Start --------------------------->
call plug#begin('~/.vim/plugged')

Plug 'https://github.com/scrooloose/nerdtree'
Plug 'davidhalter/jedi-vim'
Plug 'tmhedberg/SimpylFold'
Plug 'vim-syntastic/syntastic'
Plug 'tomasiser/vim-code-dark'
Plug 'itchyny/lightline.vim'

call plug#end()
"-> Plug End ------------------------------|

filetype plugin indent on    " required

" ---- Config Options --- 
filetype plugin on
set t_Co=256
colorscheme codedark
let g:airline_theme = 'codedark'
set nrformats-=octal
syntax on
set nu
set hlsearch
set autoindent 
set expandtab
set smartcase
set magic
set guioptions=T
set paste
set wildmenu
set ruler
set smarttab
set smartindent

set colorcolumn=88
set tabstop=4
set softtabstop=4
set shiftwidth=4
set textwidth=79

set fileformat=unix
setlocal spell spelllang=en_us

set history=250
set mouse=a
set scrolloff=999

"--- --- Plugin Configuration Settings ----------- 
filetype plugin indent on
" automatically change window's cwd to file's dir
set autochdir

" Nerdtree Config 
" Open Nerdtree if no file specified when Vim Opened
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'

" Enable folding
set foldmethod=indent
set foldlevel=99

" Enable folding with the spacebar
nnoremap <space> za


" vim Jedi Options
let python_highlight_all=1

" Syntastic (Recomened Options)

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 1

" lightline
set laststatus=2
if !has('gui_running')
  set t_Co=256
endif

